# Generated by Django 5.2.14 on 2026-06-06 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlow', '0002_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.TextField(max_length=150)),
                ('roleName', models.TextField(max_length=150)),
                ('location', models.TextField(max_length=250)),
                ('jobType', models.TextField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], max_length=150)),
                ('sourceName', models.TextField(max_length=50)),
                ('salary', models.TextField(max_length=50)),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Saved', max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
