# Generated by Django 5.2.14 on 2026-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerFlow', '0003_alter_skills_created_at_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='companyName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='applications',
            name='jobType',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], max_length=150),
        ),
        migrations.AlterField(
            model_name='applications',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='applications',
            name='roleName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='applications',
            name='salary',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applications',
            name='sourceName',
            field=models.CharField(max_length=50),
        ),
    ]
